version: "2.3"

services:
  streamserver-nginx:
    image: 613895955229.dkr.ecr.eu-central-1.amazonaws.com/atomy/streamserver-nginx:latest
    volumes:
      - ./access_log:/var/log/nginx/access_log
    ports:
      - 1935:1935